{assign var="ENABLE_RESPONSIVE" value="1" scope="global"}
{assign var="LISTING_GRID_MODE" value="grid" scope="global"}
{assign var="LISTING_PRODUCT_COLUMN_MODULE" value="3" scope="global"}
{assign var="LISTING_PRODUCT_COLUMN" value="3" scope="global"}
{assign var="LISTING_PRODUCT_LARGEDEVICE" value="3" scope="global"}
{assign var="LISTING_PRODUCT_TABLET" value="2" scope="global"}
{assign var="LISTING_PRODUCT_SMALLDEVICE" value="2" scope="global"}
{assign var="LISTING_PRODUCT_EXTRASMALLDEVICE" value="2" scope="global"}
{assign var="LISTING_PRODUCT_MOBILE" value="1" scope="global"}
